spring.datasource.url=jdbc:postgresql://database-1.csxqa60s473p.us-east-1.rds.amazonaws.com:5432/prueba1
spring.datasource.username=postgres
spring.datasource.password=Lol89123!
spring.datasource.driver-class-name=org.postgresql.Driver
spring.sql.init.encoding=UTF-8
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

