spring.application.name=proyecto_spring_boot_java
security.jwt.expiration-in-minutes=460
spring.profiles.active=dev
security.jwt.secret-key=jadklajdlkadjlashdjkahdsadaslaskjdjashjkahdkjasdhkasdkahshdkah